apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "grpc-k8s-lb.fullname" . }}
  labels:
    app: {{ template "grpc-k8s-lb.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "grpc-k8s-lb.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "grpc-k8s-lb.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          command:
          {{- range .Values.command }}
            - {{ . }}
          {{- end }}
          args: 
          {{- range .Values.args }}
            - {{ . }}
          {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
  selector:
    matchLabels:
      app: {{ template "grpc-k8s-lb.name" . }}
      release: {{ .Release.Name }}
